//ReportView.js//

/**
 * @description - File that defines the view of the report generated by LexicalChecker
 */

 //Node module imports
 const React = require('react');

 const LexicalReportView = React.createClass({

 });

 module.exports = LexicalReportView;