var style = {
  liGreen: {
    display: "inline-block",
    float: "left",
    textAlign: "center",
    border: "1px solid transparent",
    borderRadius: "4px 0px 0px 4px",
    borderColor: "#3e8f3e",
    paddingTop: "5px",
    paddingBottom: "5px",
    color: "white",
    userSelect: "none",
    backgroundImage: "linear-gradient(to bottom,#5cb85c 0,#419641 100%)",
    width: "153.2px",
    height: "50px",
    cursor: "pointer",
  },

  hoverGreen: {
    display: "inline-block",
    float: "left",
    textAlign: "center",
    border: "1px solid transparent",
    borderRadius: "4px 0px 0px 4px",
    borderColor: "#3e8f3e",
    paddingTop: "5px",
    paddingBottom: "5px",
    color: "white",
    userSelect: "none",
    backgroundImage: "linear-gradient(to bottom,#5cb85c 0,#76c376 100%)",
    width: "153.2px",
    height: "50px",
    cursor: "pointer",
  },

  liYellow: {
    display: "inline-block",
    float: "left",
    textAlign: "center",
    border: "1px solid transparent",
    borderColor: "#e38d13",
    paddingTop: "5px",
    paddingBottom: "5px",
    color: "white",
    userSelect: "none",
    backgroundImage: "linear-gradient(to bottom,#f0ad4e 0,#eb9316 100%)",
    width: "153.2px",
    height: "50px",
    cursor: "pointer",
  },

  hoverYellow: {
    display: "inline-block",
    float: "left",
    textAlign: "center",
    border: "1px solid transparent",
    borderColor: "#e38d13",
    paddingTop: "5px",
    paddingBottom: "5px",
    color: "white",
    userSelect: "none",
    backgroundImage: "linear-gradient(to bottom,#f5c684 0,#eb9316 100%)",
    width: "153.2px",
    height: "50px",
    cursor: "pointer",
  },

  liRed: {
    display: "inline-block",
    float: "left",
    textAlign: "center",
    border: "1px solid transparent",
    borderRadius: "0px 4px 4px 0px",
    borderColor: "#b92c28",
    paddingTop: "5px",
    paddingBottom: "5px",
    color: "white",
    userSelect: "none",
    backgroundImage: "linear-gradient(to bottom,#d9534f 0,#c12e2a 100%)",
    width: "153.2px",
    height: "50px",
    cursor: "pointer",
  },

  hoverRed: {
    display: "inline-block",
    float: "left",
    textAlign: "center",
    border: "1px solid transparent",
    borderRadius: "0px 4px 4px 0px",
    borderColor: "#b92c28",
    paddingTop: "5px",
    paddingBottom: "5px",
    color: "white",
    userSelect: "none",
    backgroundImage: "linear-gradient(to bottom,#e0736f 0,#c12e2a 100%)",
    width: "153.2px",
    height: "50px",
    cursor: "pointer",
  },

};

module.exports = style;
